module.exports = {
  ADD: 'ADD',
  SUBTRACT: 'SUBTRACT',
  MULTIPLY: 'MULTIPLY',
  DIVIDE: 'DIVIDE',
  SET_OPERATOR: 'SET_OPERATOR',
  DISPLAY_OPERATION: 'DISPLAY_OPERATION',
  DISPLAY: 'DISPLAY',
  DISPLAY_RESULT: 'DISPLAY_RESULT',
  SET_NEGATIVE: 'SET_NEGATIVE',
  EVAL: 'EVAL',
  C: 'C'
};